name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
    
  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download text file
      uses: actions/download-artifact@v2
      with:
      # Name of the artifact to download.
      # If unspecified, all artifacts for the run are downloaded.
      # Optional.
        name: hello-artifact

      # Destination path. Supports basic tilde expansion.
      # Optional. Default is $GITHUB_WORKSPACE
        path: ./artifacts

    - name: Display contents of file
      run: cat ./artifacts/hello.txt
  